name: Deploy Production

env:
  ENVIRONMENT: production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Set production deployment
        run: echo "Production deployment triggered (no actual deployment performed)."
